name: 'django_dbt_platform'
version: '1.0.0'

profile: 'analytics_db'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  django_dbt_platform:
    +materialized: table
